package smartcity.kni.wirtualnaapteczka;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALERGENS__LIST".
*/
public class Alergens_ListDao extends AbstractDao<Alergens_List, Long> {

    public static final String TABLENAME = "ALERGENS__LIST";

    /**
     * Properties of entity Alergens_List.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MedicineId = new Property(1, Long.class, "medicineId", false, "MEDICINE_ID");
        public final static Property AlergenId = new Property(2, Long.class, "alergenId", false, "ALERGEN_ID");
    }

    private DaoSession daoSession;

    private Query<Alergens_List> alergen_Alergens_ListListQuery;
    private Query<Alergens_List> medicine_Alergens_ListListQuery;

    public Alergens_ListDao(DaoConfig config) {
        super(config);
    }
    
    public Alergens_ListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALERGENS__LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MEDICINE_ID\" INTEGER," + // 1: medicineId
                "\"ALERGEN_ID\" INTEGER);"); // 2: alergenId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALERGENS__LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Alergens_List entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long medicineId = entity.getMedicineId();
        if (medicineId != null) {
            stmt.bindLong(2, medicineId);
        }
 
        Long alergenId = entity.getAlergenId();
        if (alergenId != null) {
            stmt.bindLong(3, alergenId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Alergens_List entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long medicineId = entity.getMedicineId();
        if (medicineId != null) {
            stmt.bindLong(2, medicineId);
        }
 
        Long alergenId = entity.getAlergenId();
        if (alergenId != null) {
            stmt.bindLong(3, alergenId);
        }
    }

    @Override
    protected final void attachEntity(Alergens_List entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Alergens_List readEntity(Cursor cursor, int offset) {
        Alergens_List entity = new Alergens_List( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // medicineId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // alergenId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Alergens_List entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMedicineId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setAlergenId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Alergens_List entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Alergens_List entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Alergens_List entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "alergens_ListList" to-many relationship of Alergen. */
    public List<Alergens_List> _queryAlergen_Alergens_ListList(Long alergenId) {
        synchronized (this) {
            if (alergen_Alergens_ListListQuery == null) {
                QueryBuilder<Alergens_List> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AlergenId.eq(null));
                alergen_Alergens_ListListQuery = queryBuilder.build();
            }
        }
        Query<Alergens_List> query = alergen_Alergens_ListListQuery.forCurrentThread();
        query.setParameter(0, alergenId);
        return query.list();
    }

    /** Internal query to resolve the "alergens_ListList" to-many relationship of Medicine. */
    public List<Alergens_List> _queryMedicine_Alergens_ListList(Long medicineId) {
        synchronized (this) {
            if (medicine_Alergens_ListListQuery == null) {
                QueryBuilder<Alergens_List> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MedicineId.eq(null));
                medicine_Alergens_ListListQuery = queryBuilder.build();
            }
        }
        Query<Alergens_List> query = medicine_Alergens_ListListQuery.forCurrentThread();
        query.setParameter(0, medicineId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAlergenDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMedicineDao().getAllColumns());
            builder.append(" FROM ALERGENS__LIST T");
            builder.append(" LEFT JOIN ALERGEN T0 ON T.\"ALERGEN_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN MEDICINE T1 ON T.\"MEDICINE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Alergens_List loadCurrentDeep(Cursor cursor, boolean lock) {
        Alergens_List entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Alergen alergen = loadCurrentOther(daoSession.getAlergenDao(), cursor, offset);
        entity.setAlergen(alergen);
        offset += daoSession.getAlergenDao().getAllColumns().length;

        Medicine medicine = loadCurrentOther(daoSession.getMedicineDao(), cursor, offset);
        entity.setMedicine(medicine);

        return entity;    
    }

    public Alergens_List loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Alergens_List> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Alergens_List> list = new ArrayList<Alergens_List>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Alergens_List> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Alergens_List> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
