package smartcity.kni.wirtualnaapteczka;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import smartcity.kni.wirtualnaapteczka.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALERGENS__LIST".
 */
@Entity(active = true)
public class Alergens_List {

    @Id(autoincrement = true)
    private Long id;
    private Long medicineId;
    private Long alergenId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient Alergens_ListDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "alergenId")
    })
    private List<Alergen> alergenList;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "medicineId")
    })
    private List<Medicine> medicineList;

    @Generated
    public Alergens_List() {
    }

    public Alergens_List(Long id) {
        this.id = id;
    }

    @Generated
    public Alergens_List(Long id, Long medicineId, Long alergenId) {
        this.id = id;
        this.medicineId = medicineId;
        this.alergenId = alergenId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAlergens_ListDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(Long medicineId) {
        this.medicineId = medicineId;
    }

    public Long getAlergenId() {
        return alergenId;
    }

    public void setAlergenId(Long alergenId) {
        this.alergenId = alergenId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Alergen> getAlergenList() {
        if (alergenList == null) {
            __throwIfDetached();
            AlergenDao targetDao = daoSession.getAlergenDao();
            List<Alergen> alergenListNew = targetDao._queryAlergens_List_AlergenList(id);
            synchronized (this) {
                if(alergenList == null) {
                    alergenList = alergenListNew;
                }
            }
        }
        return alergenList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetAlergenList() {
        alergenList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Medicine> getMedicineList() {
        if (medicineList == null) {
            __throwIfDetached();
            MedicineDao targetDao = daoSession.getMedicineDao();
            List<Medicine> medicineListNew = targetDao._queryAlergens_List_MedicineList(id);
            synchronized (this) {
                if(medicineList == null) {
                    medicineList = medicineListNew;
                }
            }
        }
        return medicineList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetMedicineList() {
        medicineList = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
