package smartcity.kni.wirtualnaapteczka;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import smartcity.kni.wirtualnaapteczka.Dose;
import smartcity.kni.wirtualnaapteczka.Alergen;
import smartcity.kni.wirtualnaapteczka.Alergens_List;
import smartcity.kni.wirtualnaapteczka.Information;
import smartcity.kni.wirtualnaapteczka.Medicine;

import smartcity.kni.wirtualnaapteczka.DoseDao;
import smartcity.kni.wirtualnaapteczka.AlergenDao;
import smartcity.kni.wirtualnaapteczka.Alergens_ListDao;
import smartcity.kni.wirtualnaapteczka.InformationDao;
import smartcity.kni.wirtualnaapteczka.MedicineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doseDaoConfig;
    private final DaoConfig alergenDaoConfig;
    private final DaoConfig alergens_ListDaoConfig;
    private final DaoConfig informationDaoConfig;
    private final DaoConfig medicineDaoConfig;

    private final DoseDao doseDao;
    private final AlergenDao alergenDao;
    private final Alergens_ListDao alergens_ListDao;
    private final InformationDao informationDao;
    private final MedicineDao medicineDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doseDaoConfig = daoConfigMap.get(DoseDao.class).clone();
        doseDaoConfig.initIdentityScope(type);

        alergenDaoConfig = daoConfigMap.get(AlergenDao.class).clone();
        alergenDaoConfig.initIdentityScope(type);

        alergens_ListDaoConfig = daoConfigMap.get(Alergens_ListDao.class).clone();
        alergens_ListDaoConfig.initIdentityScope(type);

        informationDaoConfig = daoConfigMap.get(InformationDao.class).clone();
        informationDaoConfig.initIdentityScope(type);

        medicineDaoConfig = daoConfigMap.get(MedicineDao.class).clone();
        medicineDaoConfig.initIdentityScope(type);

        doseDao = new DoseDao(doseDaoConfig, this);
        alergenDao = new AlergenDao(alergenDaoConfig, this);
        alergens_ListDao = new Alergens_ListDao(alergens_ListDaoConfig, this);
        informationDao = new InformationDao(informationDaoConfig, this);
        medicineDao = new MedicineDao(medicineDaoConfig, this);

        registerDao(Dose.class, doseDao);
        registerDao(Alergen.class, alergenDao);
        registerDao(Alergens_List.class, alergens_ListDao);
        registerDao(Information.class, informationDao);
        registerDao(Medicine.class, medicineDao);
    }
    
    public void clear() {
        doseDaoConfig.clearIdentityScope();
        alergenDaoConfig.clearIdentityScope();
        alergens_ListDaoConfig.clearIdentityScope();
        informationDaoConfig.clearIdentityScope();
        medicineDaoConfig.clearIdentityScope();
    }

    public DoseDao getDoseDao() {
        return doseDao;
    }

    public AlergenDao getAlergenDao() {
        return alergenDao;
    }

    public Alergens_ListDao getAlergens_ListDao() {
        return alergens_ListDao;
    }

    public InformationDao getInformationDao() {
        return informationDao;
    }

    public MedicineDao getMedicineDao() {
        return medicineDao;
    }

}
