package smartcity.kni.wirtualnaapteczka;

import org.greenrobot.greendao.annotation.*;

import smartcity.kni.wirtualnaapteczka.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "INFORMATION".
 */
@Entity(active = true)
public class Information {

    @Id(autoincrement = true)
    private Long id;
    private String message;
    private java.util.Date date;
    private java.util.Date time;
    private Boolean alert;
    private Boolean regular;
    private Long idMedicine;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient InformationDao myDao;

    @ToOne(joinProperty = "idMedicine")
    private Medicine medicine;

    @Generated
    private transient Long medicine__resolvedKey;

    @Generated
    public Information() {
    }

    public Information(Long id) {
        this.id = id;
    }

    @Generated
    public Information(Long id, String message, java.util.Date date, java.util.Date time, Boolean alert, Boolean regular, Long idMedicine) {
        this.id = id;
        this.message = message;
        this.date = date;
        this.time = time;
        this.alert = alert;
        this.regular = regular;
        this.idMedicine = idMedicine;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getInformationDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Boolean getAlert() {
        return alert;
    }

    public void setAlert(Boolean alert) {
        this.alert = alert;
    }

    public Boolean getRegular() {
        return regular;
    }

    public void setRegular(Boolean regular) {
        this.regular = regular;
    }

    public Long getIdMedicine() {
        return idMedicine;
    }

    public void setIdMedicine(Long idMedicine) {
        this.idMedicine = idMedicine;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Medicine getMedicine() {
        Long __key = this.idMedicine;
        if (medicine__resolvedKey == null || !medicine__resolvedKey.equals(__key)) {
            __throwIfDetached();
            MedicineDao targetDao = daoSession.getMedicineDao();
            Medicine medicineNew = targetDao.load(__key);
            synchronized (this) {
                medicine = medicineNew;
            	medicine__resolvedKey = __key;
            }
        }
        return medicine;
    }

    @Generated
    public void setMedicine(Medicine medicine) {
        synchronized (this) {
            this.medicine = medicine;
            idMedicine = medicine == null ? null : medicine.getId();
            medicine__resolvedKey = idMedicine;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
