package smartcity.kni.wirtualnaapteczka;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICINE".
*/
public class MedicineDao extends AbstractDao<Medicine, Long> {

    public static final String TABLENAME = "MEDICINE";

    /**
     * Properties of entity Medicine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property ExpiryDate = new Property(3, java.util.Date.class, "expiryDate", false, "EXPIRY_DATE");
        public final static Property Tag = new Property(4, String.class, "tag", false, "TAG");
        public final static Property EAN = new Property(5, String.class, "EAN", false, "EAN");
        public final static Property IdInformation = new Property(6, Long.class, "idInformation", false, "ID_INFORMATION");
        public final static Property IdDose = new Property(7, Long.class, "idDose", false, "ID_DOSE");
        public final static Property MedicineId = new Property(8, Long.class, "medicineId", false, "MEDICINE_ID");
        public final static Property IdMedicine = new Property(9, Long.class, "idMedicine", false, "ID_MEDICINE");
    }

    private DaoSession daoSession;

    private Query<Medicine> alergens_List_MedicineListQuery;
    private Query<Medicine> dose_MedicineListQuery;
    private Query<Medicine> information_MedicineListQuery;

    public MedicineDao(DaoConfig config) {
        super(config);
    }
    
    public MedicineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DESCRIPTION\" TEXT," + // 2: description
                "\"EXPIRY_DATE\" INTEGER," + // 3: expiryDate
                "\"TAG\" TEXT," + // 4: tag
                "\"EAN\" TEXT," + // 5: EAN
                "\"ID_INFORMATION\" INTEGER," + // 6: idInformation
                "\"ID_DOSE\" INTEGER," + // 7: idDose
                "\"MEDICINE_ID\" INTEGER," + // 8: medicineId
                "\"ID_MEDICINE\" INTEGER);"); // 9: idMedicine
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICINE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Medicine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
 
        java.util.Date expiryDate = entity.getExpiryDate();
        if (expiryDate != null) {
            stmt.bindLong(4, expiryDate.getTime());
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(5, tag);
        }
 
        String EAN = entity.getEAN();
        if (EAN != null) {
            stmt.bindString(6, EAN);
        }
 
        Long idInformation = entity.getIdInformation();
        if (idInformation != null) {
            stmt.bindLong(7, idInformation);
        }
 
        Long idDose = entity.getIdDose();
        if (idDose != null) {
            stmt.bindLong(8, idDose);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Medicine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
 
        java.util.Date expiryDate = entity.getExpiryDate();
        if (expiryDate != null) {
            stmt.bindLong(4, expiryDate.getTime());
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(5, tag);
        }
 
        String EAN = entity.getEAN();
        if (EAN != null) {
            stmt.bindString(6, EAN);
        }
 
        Long idInformation = entity.getIdInformation();
        if (idInformation != null) {
            stmt.bindLong(7, idInformation);
        }
 
        Long idDose = entity.getIdDose();
        if (idDose != null) {
            stmt.bindLong(8, idDose);
        }
    }

    @Override
    protected final void attachEntity(Medicine entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Medicine readEntity(Cursor cursor, int offset) {
        Medicine entity = new Medicine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // expiryDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tag
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // EAN
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // idInformation
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // idDose
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Medicine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExpiryDate(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setTag(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEAN(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIdInformation(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setIdDose(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Medicine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Medicine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Medicine entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "medicineList" to-many relationship of Alergens_List. */
    public List<Medicine> _queryAlergens_List_MedicineList(Long medicineId) {
        synchronized (this) {
            if (alergens_List_MedicineListQuery == null) {
                QueryBuilder<Medicine> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MedicineId.eq(null));
                alergens_List_MedicineListQuery = queryBuilder.build();
            }
        }
        Query<Medicine> query = alergens_List_MedicineListQuery.forCurrentThread();
        query.setParameter(0, medicineId);
        return query.list();
    }

    /** Internal query to resolve the "medicineList" to-many relationship of Dose. */
    public List<Medicine> _queryDose_MedicineList(Long idMedicine) {
        synchronized (this) {
            if (dose_MedicineListQuery == null) {
                QueryBuilder<Medicine> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdMedicine.eq(null));
                dose_MedicineListQuery = queryBuilder.build();
            }
        }
        Query<Medicine> query = dose_MedicineListQuery.forCurrentThread();
        query.setParameter(0, idMedicine);
        return query.list();
    }

    /** Internal query to resolve the "medicineList" to-many relationship of Information. */
    public List<Medicine> _queryInformation_MedicineList(Long idInformation) {
        synchronized (this) {
            if (information_MedicineListQuery == null) {
                QueryBuilder<Medicine> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdInformation.eq(null));
                information_MedicineListQuery = queryBuilder.build();
            }
        }
        Query<Medicine> query = information_MedicineListQuery.forCurrentThread();
        query.setParameter(0, idInformation);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAlergens_ListDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDoseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getInformationDao().getAllColumns());
            builder.append(" FROM MEDICINE T");
            builder.append(" LEFT JOIN ALERGENS__LIST T0 ON T.\"MEDICINE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN DOSE T1 ON T.\"ID_MEDICINE\"=T1.\"_id\"");
            builder.append(" LEFT JOIN INFORMATION T2 ON T.\"ID_INFORMATION\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Medicine loadCurrentDeep(Cursor cursor, boolean lock) {
        Medicine entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Alergens_List alergens_List = loadCurrentOther(daoSession.getAlergens_ListDao(), cursor, offset);
        entity.setAlergens_List(alergens_List);
        offset += daoSession.getAlergens_ListDao().getAllColumns().length;

        Dose dose = loadCurrentOther(daoSession.getDoseDao(), cursor, offset);
        entity.setDose(dose);
        offset += daoSession.getDoseDao().getAllColumns().length;

        Information information = loadCurrentOther(daoSession.getInformationDao(), cursor, offset);
        entity.setInformation(information);

        return entity;    
    }

    public Medicine loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Medicine> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Medicine> list = new ArrayList<Medicine>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Medicine> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Medicine> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
